version: 2
updates:
  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: weekly
      day: saturday
      time: "02:00"
      timezone: "Australia/Brisbane"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "02:00"
      timezone: "Australia/Brisbane"
