---
name: Python Linting - Ruff

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.3'
      - name: Running pylint
        run: |
          python -m pip install -r api/requirements.txt
          python -m pip install ruff
          ruff api/*.py
